package main

import (
	"fmt"
	"go/ast"
	"log"
	"sort"
	"strings"
)

// generateRustCode writes serde types for every butlerd message, plus the
// request, notification and server-request plumbing a Rust client needs.
//
// Nullability follows Go: a pointer field decodes as Option<T> because the
// daemon writes `null` for a nil pointer whether or not the field is marked
// @optional. Every field carries serde(default) so a newer daemon adding
// fields, or omitting empty ones, never breaks an older client, and every
// non-Option field accepts `null` as its default, since Go writes `null`
// for nil slices and maps too.
func (gc *generousContext) generateRustCode(outPath string) error {
	gc.task("Generating Rust bindings")

	doc := gc.newPathDoc(outPath)

	scope := newScope(gc)
	scope.assimilateAll()

	doc.line("// These bindings were generated by generous. Do not edit.")
	doc.line("// See <https://docs.itch.zone/butlerd/master/> for a human-friendly documentation")
	doc.line("")
	doc.line("#![allow(non_camel_case_types, dead_code, deprecated, clippy::all)]")
	doc.line("")
	doc.line("use std::collections::HashMap;")
	doc.line("")
	doc.line("use serde::{Deserialize, Serialize};")
	doc.line("use serde_json::Value;")
	doc.line("")
	doc.line("use %s::{Notification, Request, ServerRequest};", gc.SupportPath)
	doc.line("")
	doc.line("/// RFC3339 date string")
	doc.line("pub type RFCDate = String;")
	doc.line("")
	doc.line("/// Go marshals a nil slice, map or pointer as `null`, which serde would")
	doc.line("/// reject for a non-Option field; `serde(default)` alone only covers a")
	doc.line("/// missing key.")
	doc.line("fn null_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>")
	doc.line("where")
	doc.line("    D: serde::Deserializer<'de>,")
	doc.line("    T: Default + Deserialize<'de>,")
	doc.line("{")
	doc.line("    Ok(Option::<T>::deserialize(deserializer)?.unwrap_or_default())")
	doc.line("}")

	docLines := func(indent string, lines []string) {
		for _, line := range lines {
			if line == "" {
				doc.line("%s///", indent)
			} else {
				doc.line("%s/// %s", indent, line)
			}
		}
	}

	deprecatedAttr := func(indent string, note string) {
		if note != "" {
			doc.line("%s#[deprecated(note = %s)]", indent, rustString(note))
		}
	}

	// Struct fields whose type refers back to the containing struct, directly
	// or through other structs, need heap indirection or Rust cannot size
	// them. Vec and HashMap already indirect, so only bare or pointer fields
	// count as edges.
	boxed := cyclicFields(scope)

	emitStruct := func(entry *entryInfo) {
		doc.line("")
		switch entry.kind {
		case entryKindParams:
			doc.line("/// Params for %s", entry.name)
		case entryKindResult:
			params := scope.findEntry(strings.TrimSuffix(entry.typeName, "Result") + "Params")
			if params != nil {
				doc.line("/// Result for %s", params.name)
			}
		case entryKindNotification:
			doc.line("/// Payload for %s", entry.name)
		default:
			docLines("", entry.doc)
		}
		deprecatedAttr("", entry.deprecated)
		doc.line("#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]")
		doc.line("pub struct %s {", entry.typeName)
		for _, sf := range entry.structFields {
			docLines("    ", sf.doc)
			optional := sf.optional || isPointer(sf.typeNode)
			rustType := rustTypeOf(sf.typeNode)
			if boxed[entry.typeName+"."+sf.name] {
				rustType = "Box<" + rustType + ">"
			}
			if optional {
				rustType = "Option<" + rustType + ">"
				doc.line("    #[serde(rename = %s, default, skip_serializing_if = \"Option::is_none\")]", rustString(sf.name))
			} else {
				doc.line("    #[serde(rename = %s, default, deserialize_with = \"null_default\")]", rustString(sf.name))
			}
			doc.line("    pub %s: %s,", rustFieldName(sf.name), rustType)
		}
		doc.line("}")
	}

	emitEnum := func(entry *entryInfo) {
		doc.line("")
		docLines("", entry.doc)
		underlying := entry.typeSpec.Type.(*ast.Ident).Name
		if underlying == "string" {
			doc.line("#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]")
			doc.line("pub enum %s {", entry.typeName)
			// Go's zero value is the empty string, so a variant for "" is
			// the natural default; otherwise the catch-all is.
			hasZero := false
			catchAll := "Unknown"
			for _, val := range entry.enumValues {
				if str, ok := val.jsonValue.(string); ok && str == "" {
					hasZero = true
				}
				if rustVariantName(val.name) == "Unknown" {
					catchAll = "Other"
				}
			}
			for _, val := range entry.enumValues {
				docLines("    ", val.doc)
				str, ok := val.jsonValue.(string)
				if !ok {
					log.Fatalf("%s.%s: string enum with non-string value %v", entry.typeName, val.name, val.jsonValue)
				}
				if str == "" {
					doc.line("    #[default]")
				}
				doc.line("    #[serde(rename = %s)]", rustString(str))
				doc.line("    %s,", rustVariantName(val.name))
			}
			// A value this build of the bindings has never heard of still
			// decodes, so a newer daemon does not break the client. It has
			// no wire form, so sending it is an error rather than junk.
			doc.line("    /// Any value not listed above.")
			if !hasZero {
				doc.line("    #[default]")
			}
			doc.line("    #[serde(other, skip_serializing)]")
			doc.line("    %s,", catchAll)
			doc.line("}")
			return
		}
		// Numeric enums stay open: the wire value is the type, the known
		// values are associated constants.
		doc.line("#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]")
		doc.line("#[serde(transparent)]")
		doc.line("pub struct %s(pub %s);", entry.typeName, rustPrimitive(underlying))
		doc.line("")
		doc.line("impl %s {", entry.typeName)
		for _, val := range entry.enumValues {
			docLines("    ", val.doc)
			doc.line("    pub const %s: %s = %s(%s);", rustConstName(val.name), entry.typeName, entry.typeName, val.value)
		}
		doc.line("}")
	}

	emitAlias := func(entry *entryInfo) {
		doc.line("")
		docLines("", entry.doc)
		doc.line("pub type %s = %s;", entry.typeName, rustTypeOf(entry.typeSpec.Type))
	}

	var clientRequests []*entryInfo
	var serverRequests []*entryInfo
	var notifications []*entryInfo

	for _, category := range scope.categoryList {
		cat := scope.categories[category]
		doc.line("")
		doc.line("// ---- %s", category)
		for _, entry := range cat.entries {
			switch entry.typeKind {
			case entryTypeKindStruct:
				emitStruct(entry)
			case entryTypeKindEnum:
				emitEnum(entry)
			case entryTypeKindArrayAlias, entryTypeKindAlias:
				emitAlias(entry)
			}

			switch entry.kind {
			case entryKindParams:
				resultName := strings.TrimSuffix(entry.typeName, "Params") + "Result"
				result := scope.findEntry(resultName)
				if result == nil {
					log.Printf("Warning: %q doesn't have a Result equivalent", entry.typeName)
					resultName = "()"
				}
				doc.line("")
				doc.line("impl Request for %s {", entry.typeName)
				doc.line("    const METHOD: &'static str = %s;", rustString(entry.name))
				doc.line("    type Result = %s;", resultName)
				doc.line("}")
				switch entry.caller {
				case callerClient:
					clientRequests = append(clientRequests, entry)
				case callerServer:
					serverRequests = append(serverRequests, entry)
				}
			case entryKindNotification:
				notifications = append(notifications, entry)
			}
		}
	}

	// A dispatch enum for everything the daemon sends on its own.
	doc.line("")
	doc.line("// ---- Dispatch")
	doc.line("")
	doc.line("/// Every notification the daemon can send, decoded from its method name.")
	doc.line("#[derive(Debug, Clone, PartialEq)]")
	doc.line("pub enum AnyNotification {")
	for _, entry := range notifications {
		docLines("    ", entry.doc)
		doc.line("    %s(%s),", rustVariantName(strings.ReplaceAll(entry.name, ".", "")), entry.typeName)
	}
	doc.line("    /// A method these bindings do not know.")
	doc.line("    Unknown { method: String, params: Value },")
	doc.line("}")
	doc.line("")
	doc.line("impl AnyNotification {")
	doc.line("    pub fn decode(method: &str, params: Value) -> Result<Self, serde_json::Error> {")
	doc.line("        Ok(match method {")
	for _, entry := range notifications {
		doc.line("            %s => Self::%s(serde_json::from_value(params)?),", rustString(entry.name), rustVariantName(strings.ReplaceAll(entry.name, ".", "")))
	}
	doc.line("            _ => Self::Unknown {")
	doc.line("                method: method.to_string(),")
	doc.line("                params,")
	doc.line("            },")
	doc.line("        })")
	doc.line("    }")
	doc.line("}")

	for _, entry := range notifications {
		doc.line("")
		doc.line("impl Notification for %s {", entry.typeName)
		doc.line("    const METHOD: &'static str = %s;", rustString(entry.name))
		doc.line("}")
	}

	doc.line("")
	doc.line("/// Every request the daemon can make of the client mid-call, decoded")
	doc.line("/// from its method name. The client must answer each with the matching")
	doc.line("/// Result type.")
	doc.line("#[derive(Debug, Clone, PartialEq)]")
	doc.line("pub enum AnyServerRequest {")
	for _, entry := range serverRequests {
		docLines("    ", entry.doc)
		doc.line("    %s(%s),", rustVariantName(strings.ReplaceAll(entry.name, ".", "")), entry.typeName)
	}
	doc.line("    /// A method these bindings do not know.")
	doc.line("    Unknown { method: String, params: Value },")
	doc.line("}")
	doc.line("")
	doc.line("impl AnyServerRequest {")
	doc.line("    pub fn decode(method: &str, params: Value) -> Result<Self, serde_json::Error> {")
	doc.line("        Ok(match method {")
	for _, entry := range serverRequests {
		doc.line("            %s => Self::%s(serde_json::from_value(params)?),", rustString(entry.name), rustVariantName(strings.ReplaceAll(entry.name, ".", "")))
	}
	doc.line("            _ => Self::Unknown {")
	doc.line("                method: method.to_string(),")
	doc.line("                params,")
	doc.line("            },")
	doc.line("        })")
	doc.line("    }")
	doc.line("}")

	for _, entry := range serverRequests {
		doc.line("")
		doc.line("impl ServerRequest for %s {}", entry.typeName)
	}

	// Anything a field refers to that no assimilated file defines would
	// fail to compile on the Rust side; say so here where it is easy to fix.
	var missing []string
	seen := map[string]bool{}
	for _, entry := range scope.entries {
		for _, sf := range entry.structFields {
			for _, name := range namedTypes(sf.typeNode) {
				if _, ok := scope.entries[name]; !ok && !seen[name] {
					seen[name] = true
					missing = append(missing, name)
				}
			}
		}
	}
	sort.Strings(missing)
	for _, name := range missing {
		log.Printf("Warning: type %q is referenced but not defined in any assimilated file", name)
	}

	log.Printf("%d client requests, %d server requests, %d notifications", len(clientRequests), len(serverRequests), len(notifications))

	doc.commit("")
	doc.write()

	return nil
}

// directEdge names the struct a field embeds without a container, if any.
func directEdge(e ast.Expr) (string, bool) {
	switch node := e.(type) {
	case *ast.Ident:
		if !isGoPrimitive(node.Name) {
			return node.Name, true
		}
	case *ast.StarExpr:
		return directEdge(node.X)
	case *ast.SelectorExpr:
		if node.Sel.Name != "Time" {
			return node.Sel.Name, true
		}
	}
	return "", false
}

// cyclicFields returns "Type.jsonField" for every field on a cycle of direct
// struct references.
func cyclicFields(s *scope) map[string]bool {
	edges := map[string][]string{}
	for name, entry := range s.entries {
		if entry.typeKind != entryTypeKindStruct {
			continue
		}
		for _, sf := range entry.structFields {
			if target, ok := directEdge(sf.typeNode); ok {
				if t, known := s.entries[target]; known && t.typeKind == entryTypeKindStruct {
					edges[name] = append(edges[name], target)
				}
			}
		}
	}
	reaches := func(from, to string) bool {
		seen := map[string]bool{}
		stack := []string{from}
		for len(stack) > 0 {
			cur := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			if cur == to {
				return true
			}
			if seen[cur] {
				continue
			}
			seen[cur] = true
			stack = append(stack, edges[cur]...)
		}
		return false
	}
	result := map[string]bool{}
	for name, entry := range s.entries {
		if entry.typeKind != entryTypeKindStruct {
			continue
		}
		for _, sf := range entry.structFields {
			target, ok := directEdge(sf.typeNode)
			if !ok {
				continue
			}
			if t, known := s.entries[target]; known && t.typeKind == entryTypeKindStruct && reaches(target, name) {
				result[name+"."+sf.name] = true
			}
		}
	}
	return result
}

func isPointer(e ast.Expr) bool {
	_, ok := e.(*ast.StarExpr)
	return ok
}

// rustPrimitive maps a Go builtin to its Rust type; other names pass through.
// Every integer widens to 64 bits, since JSON does not preserve width.
func rustPrimitive(goType string) string {
	switch goType {
	case "string":
		return "String"
	case "int", "int8", "int16", "int32", "int64":
		return "i64"
	case "uint", "uint8", "uint16", "uint32", "uint64", "byte":
		return "u64"
	case "float32", "float64":
		return "f64"
	case "bool":
		return "bool"
	case "any":
		return "Value"
	}
	return goType
}

func isGoPrimitive(name string) bool {
	switch name {
	case "string", "bool", "any",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "byte",
		"float32", "float64":
		return true
	}
	return false
}

// rustTypeOf maps a Go type expression to the Rust type it decodes into.
// Pointers are transparent here; the caller decides on Option.
func rustTypeOf(e ast.Expr) string {
	switch node := e.(type) {
	case *ast.Ident:
		return rustPrimitive(node.Name)
	case *ast.StarExpr:
		return rustTypeOf(node.X)
	case *ast.SelectorExpr:
		if node.Sel.Name == "Time" {
			return "RFCDate"
		}
		return node.Sel.Name
	case *ast.ArrayType:
		return "Vec<" + rustTypeOf(node.Elt) + ">"
	case *ast.MapType:
		return "HashMap<" + rustTypeOf(node.Key) + ", " + rustTypeOf(node.Value) + ">"
	case *ast.InterfaceType:
		return "Value"
	default:
		return fmt.Sprintf("%#v", node)
	}
}

// namedTypes lists the user-defined type names an expression mentions.
func namedTypes(e ast.Expr) []string {
	switch node := e.(type) {
	case *ast.Ident:
		if !isGoPrimitive(node.Name) {
			return []string{node.Name}
		}
	case *ast.StarExpr:
		return namedTypes(node.X)
	case *ast.SelectorExpr:
		if node.Sel.Name != "Time" {
			return []string{node.Sel.Name}
		}
	case *ast.ArrayType:
		return namedTypes(node.Elt)
	case *ast.MapType:
		return append(namedTypes(node.Key), namedTypes(node.Value)...)
	}
	return nil
}

var rustKeywords = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "crate": true,
	"else": true, "enum": true, "extern": true, "false": true, "fn": true,
	"for": true, "if": true, "impl": true, "in": true, "let": true, "loop": true,
	"match": true, "mod": true, "move": true, "mut": true, "pub": true, "ref": true,
	"return": true, "static": true, "struct": true, "super": true, "trait": true,
	"true": true, "type": true, "unsafe": true, "use": true, "where": true,
	"while": true, "async": true, "await": true, "dyn": true,
}

// rustFieldName turns a JSON name like installLocationID into
// install_location_id, escaping Rust keywords.
func rustFieldName(jsonName string) string {
	snake := toSnake(jsonName)
	if rustKeywords[snake] {
		return "r#" + snake
	}
	return snake
}

func toSnake(name string) string {
	var out strings.Builder
	runes := []rune(name)
	for i, r := range runes {
		if isUpper(r) {
			prevLowerOrDigit := i > 0 && (isLower(runes[i-1]) || isDigit(runes[i-1]))
			nextLower := i+1 < len(runes) && isLower(runes[i+1])
			prevUpper := i > 0 && isUpper(runes[i-1])
			if prevLowerOrDigit || (prevUpper && nextLower) {
				out.WriteRune('_')
			}
			out.WriteRune(r + ('a' - 'A'))
		} else {
			out.WriteRune(r)
		}
	}
	return out.String()
}

// rustVariantName makes a CamelCase identifier; names that start with a
// digit (Architectures "386") get a leading underscore, like the TS output.
func rustVariantName(name string) string {
	if name == "" {
		return "Empty"
	}
	if isDigit([]rune(name)[0]) {
		return "_" + name
	}
	return name
}

func rustConstName(name string) string {
	return strings.ToUpper(toSnake(rustVariantName(name)))
}

func rustString(s string) string {
	return fmt.Sprintf("%q", s)
}

func isUpper(r rune) bool { return r >= 'A' && r <= 'Z' }
func isLower(r rune) bool { return r >= 'a' && r <= 'z' }
func isDigit(r rune) bool { return r >= '0' && r <= '9' }
